### ISSUE TITLE
Одна переменная - один сенс

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-arrays#1]
https://github.com/Alex-it-work/JS-arrays/blob/72ca12c16bb71401db772e777e729bb9a4d8483e/js/index.js#L15
- это пока, конечно, просто учеба, но тут одна переменная используется для двух целей, что не есть хорошо в реальном коде. Тут, как вариант, можно вводить второй переметр. Рекомендация, исправлять не обязательно.

**Comment by Alex-it-work** [comment]
понял о чем речь, согласен
++
