### ISSUE TITLE
оптимальность

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-arrays#5]
https://github.com/Alex-it-work/JS-arrays/blob/72ca12c16bb71401db772e777e729bb9a4d8483e/js/index.js#L170
- здесь нет смысла делать проверку для каждого элемента, мы и так явно знаем, что особое поведение именно для 0го. А так нам приходится проверку делать ровно столько раз, сколько элементов. Прямо тут это не критично по времени, но задачи бывают разные, а так как это веб, то нехорошо заставлять пользователя ждать)

**Comment by Alex-it-work** [comment]
компьютер тоже не любит делать ненужную работу)
++
